// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tP-t5KOSc9G-jfmJ7s7ezbMcnW1mk0E',
    appId: '1:730014822368:web:49384928c123408ec58585',
    messagingSenderId: '730014822368',
    projectId: 'dustbuster-d9b9f',
    authDomain: 'dustbuster-d9b9f.firebaseapp.com',
    storageBucket: 'dustbuster-d9b9f.appspot.com',
    measurementId: 'G-YSEC2X48LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4ApZSQGC7zJ0qGjAITgkXyA98JV_f_Q',
    appId: '1:730014822368:android:d56f6dfdaff5d014c58585',
    messagingSenderId: '730014822368',
    projectId: 'dustbuster-d9b9f',
    storageBucket: 'dustbuster-d9b9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBUKP4-UO4qa73TBWbGAKTzWWAga-xFU',
    appId: '1:730014822368:ios:26569a4fc25fca7bc58585',
    messagingSenderId: '730014822368',
    projectId: 'dustbuster-d9b9f',
    storageBucket: 'dustbuster-d9b9f.appspot.com',
    iosBundleId: 'com.example.partner3clean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBUKP4-UO4qa73TBWbGAKTzWWAga-xFU',
    appId: '1:730014822368:ios:916e6b960454e570c58585',
    messagingSenderId: '730014822368',
    projectId: 'dustbuster-d9b9f',
    storageBucket: 'dustbuster-d9b9f.appspot.com',
    iosBundleId: 'com.example.partner3clean.RunnerTests',
  );
}
